# https://chrome.google.com/webstore/detail/mailto/gppbppehiogfokmpligejhaepeopajdf
# https://e.mail.ru/compose/?to={to}
---
configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_files:
  - .bash_profile
  - .gitignore
  - .gitconfig
  - .inputrc
  - .vimrc
  - .osx.sh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - spectralkh/tap
  - homebrew/cask-versions
  - dart-lang/dart
  - heroku/brew
  - hudochenkov/sshpass
#  - adoptopenjdk/openjdk

homebrew_installed_packages:
  - autoconf
  - ansible-lint
  - node
  - curl
  - highlight
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - gcc
  - cmake
  - asio
  - boost
  - go
  - scala
  - erlang
  - ghc
  - wireshark
  - consul
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - php
  - ssh-copy-id
  - openssl
  - wget
  - thefuck
  - xvid
  - vim
  - yasm
  - youtube-dl
  - unrar
  - netdata
  - pkg-config
  - perl
  - libuv
  - heroku
  - jpeg
  - watchman
  - imagemagick
  - ffmpeg
  - sbt
  - fontconfig
  - freetype
  - faac
  - dart
  - rust
  - git-flow
  - usbmuxd
  - libimobiledevice
  - ideviceinstaller
  - ios-deploy
  - cocoapods
  - fish
  - sshpass
  - libsass

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - whatsapp
  - intel-power-gadget
  - keepassx
  - folx
  - vk-messenger
  - 1password
  - flutter
  - visual-studio-code-insiders
  - docker
  - dropbox
  - zoomus
  - dotnet-sdk
  - firefox-developer-edition
  - google-chrome-beta
  - google-cloud-sdk
  - iina
  - anki
  - java
  - adoptopenjdk
  - adoptopenjdk8
  - keka-beta
  - jetbrains-toolbox
  - wireshark
  - macdown
  - steam
  - kitematic
  - charles-beta
  - microsoft-remote-desktop-beta
  - tunnelblick
  - virtualbox-beta
  - 4k-video-downloader
  - teamviewer
  - tor-browser
  - zeplin
  - postman
  - handbrake-nightly
  - vagrant
  - vagrant-manager
  - adobe-creative-cloud
  - skype
  - xquartz
  - tunnelbear
  - telegram

osx_script: "./files/dotfiles/.osx.sh"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: yarn
yarn_packages:
  - name: bower
  - name: pm2
  - name: typescript
  - name: vtop
  - name: node-sass
  - name: now
  - name: webtorrent-cli
  - name: electron
  - name: "@angular/cli"
  - name: gatsby-cli
  - name: create-react-app
  - name: react-native-cli
  - name: verdaccio
  - name: json
# yarn global add bower pm2 typescript vtop node-sass now webtorrent-cli electron "@angular/cli" gatsby-cli create-react-app react-native-cli verdaccio json
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
